### ISSUE TITLE
Systray icon not showing in wayland

### ISSUE THREAD

**Issue by maru-sama** [flathub/org.rncbc.qpwgraph#10]
Hi,

Since current ubuntu 22.04 does not include this nice application I went the flatpak route. What I noticed after some time was that hte systray icon was not showing. So when I closed the window I was not able to re-open it again. I switched to X for testing and there the systray icon is showing correctly. As  a last test I compiled the application myself and also here the systray icon showed up correctly so I think it has something todo with the flatpak packaging.

**Comment by maru-sama** [comment]
I forgot to mention, that when starting from the CLI I see the following warnings...
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)

**Comment by travier** [comment]
Duplicate of https://github.com/flathub/org.rncbc.qpwgraph/issues/3

**Comment by rncbc** [comment]
not quite a duplicate of #3, this is about the nice ameneties you miss by going wayland all the way; the flatpak build here forces `cmake -DCONFIG_WAYLAND=ON` which was and still is reluctantly indulged upstream (me) mind you ;) though flatpak'ers made me do it :/ that said, you're completely on your own while running flatpaks on those systems of yore...

**Comment by maru-sama** [comment]
Hi Rui,
I  can confirm this. In the end I compiled the app myself and now even with wayland enabled the icon is showing up nicely. I honestly did not mind the icon not being available but that you were able to start the application twice with the flatpak. With the native application it does not do that either.

**Comment by hfiguiere** [comment]
you can remove the wayland socket and that will test pure X11.

My take about Qt and Wayland is that Qt is so buggy that upstream disable Wayland when run in a GNOME session. (the patch is removed in the KDE SDK)

**Comment by maru-sama** [comment]
@hfiguiere can i do this myself without the need to recreate the flatpack?

**Comment by hfiguiere** [comment]
btw that doesn't mean your problem will be solved. I just indicate how to run it without using QtWayland QPA.

**Comment by maru-sama** [comment]
I ran a quick test, With the wayland socket disabled the tray icon shows up fine. I also no longer get the error

**Comment by rncbc** [comment]
does this means the -DCONFIG_WAYLAND is bonkers? I'm all in with geting rid rid of it for good ;)

**Comment by travier** [comment]
Let's keep this one to track the fix for this issue.

**Comment by travier** [comment]
Another option is to simply disable the system try for this Flatpak

**Comment by maru-sama** [comment]
@travier the changes are permanent yes, but I guess users will wonder that functionality like the systray icon is not available in the flatpak and will file bugs. Furthermore without wayland it works just fine.

**Comment by rncbc** [comment]
just set `--socket=x11` and remove the `--socket=wayland` and `-DCONFIG_WAYLAND=ON` from the flatpak build config and it probably will work out fine, in most if not all environments and systems.

**Comment by rncbc** [comment]
well, i'm about to do it (drop wayland crap)...

**Comment by travier** [comment]
Well, Wayland is the future (and present) for graphical environments on Linux so I'd say it's a bit sad to drop support for it. Hopefully we can figure out the issue for this one at some point.

**Comment by rncbc** [comment]
wayland might be the future indeed, but for the present and some recent past is way from mature

besides, and probably on all the linux DAWs that support native Linux plugin GUIs: XCB/X11 is the standard and the norm for the times to come; wayland is quite way ahead and out-of-focus in this particular niche, that I'm especially found :)

iow. I'll leave here a warning: don't even think on getting this wayland-purity-law into qtractor, ever: it will cause me a serious meltdown, if not failing miserably :)

**Comment by travier** [comment]
Definitely agree that thinks should work first which is why I'm not against this change, just saddened that we had to do this.
Hopefully we can figure out a fix for the system tray icon on Wayland.

**Comment by travier** [comment]
Definitely agree that thinks should work first which is why I'm not against this change, just saddened that we had to do this.
Hopefully we can figure out a fix for the system tray icon on Wayland.

**Comment by rncbc** [comment]
it's not only the system-tray icon: there are more... take for example: https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/51

**Comment by maru-sama** [comment]
This has been apparently fixed in 3b7f99679e3085a5e6e2232c64552dc9930c278a so I am closing this issue.

**Comment by travier** [comment]
Well, I'd say it's not fixed, only worked around, so we could keep this open until we fix it for Wayland but it's up to you. Or I can make another issue.

**Comment by rncbc** [comment]
tip: time to move on to qt6?

**Comment by travier** [comment]
There are Qt 6.3 (KDE) Runtime so we can definitely try that

**Comment by boredsquirrel** [comment]
I dont know if this is tracked somewhere else. But with

```
[Context]
sockets=!x11;wayland;

[Environment]
QT_QPA_PLATFORM=wayland
```

The current Flatpak version runs fine, shows the tray icon, the toolbars are draggable (they are not standalone windows but dont vanish into nothingness).

Everything works as expected.
